codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: up
  range: "50...90"
ignore:
  - "de.uhd.ifi.se.decision.management.eclipse/src/de/uhd/ifi/se/decision/management/eclipse/event"
  - "de.uhd.ifi.se.decision.management.eclipse/src/de/uhd/ifi/se/decision/management/eclipse/Activator.java"